services:
  app:  # Название сервиса
    build:
      context: .  # Указывает на текущую папку, где находится Dockerfile
    ports:
      - "5000:5000"  # Проброс локального порта в контейнер
    volumes:
      - .:/app  # Пробрасывает текущую директорию в контейнер, чтобы изменения применялись сразу
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:nikitatnm2@db/balance

    depends_on:  # Зависимость от другого контейнера
      - db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]


  db:  # Контейнер для базы данных
    image: postgres:13  # Используем образ PostgreSQL
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data  # Пробрасываем структуру хранилища в контейнер
    environment:
      POSTGRES_DB: balance  # Имя базы данных
      POSTGRES_USER: postgres  # Имя пользователя базы данных
      POSTGRES_PASSWORD: nikitatnm2  # Пароль пользователя базы данных

volumes:
  db_data:  # Определяем том для хранения данных Postgres